---

- name: pull git repo
  register: gitstatus
  git: accept_hostkey=yes
       force=yes
       repo=git@github.com:timesqueezer/fmexp.git
       dest={{ app_path }}

- name: ensure the directory is owned by matz but writable by the http group
  file: owner=matz group=http state=directory path={{ app_path }}

- name: install pip stuff into virtualenv
  pip: state=latest
       requirements={{ app_path }}/requirements.txt
       virtualenv={{ app_path }}/env
       virtualenv_command=virtualenv3

- name: install node stuff
  command: /usr/bin/make frontend chdir={{ app_path }}

- name: build frontend
  command: /usr/bin/make {{ app_name }}-frontend chdir={{ app_path }}

- name: migrate database
  command: chdir={{ app_path }} env/bin/flask db upgrade
  environment:
    FLASK_APP: fmexp
    FMEXP_INSTANCE_PATH: '{{ instance_path }}'
  register: migrate

- debug: msg="{{ item }}"
  with_items: '{{ migrate.stderr_lines|default(omit) }}'
  when: migrate.changed

- name: touch uwsgi vassal
  file: state=touch path=/etc/uwsgi/vassals/{{ app_name }}.ini
