---

- name: install system packages
  pacman: name=git,python-virtualenv,python-pip,uwsgi,uwsgi-plugin-python,yarn state=present update_cache=yes

- name: create empty directory to clone into
  file: owner=matz group=http mode=770 path={{ app_path }} state=directory

- name: create nginx log directory
  file: owner=http group=log mode=750 state=directory path=/var/log/nginx/{{ domain }}

- name: copy vhost
  template: src=nginx.conf.j2 dest=/etc/nginx/vhosts/{{ app_name }}.conf owner=root group=root mode=750

- name: create uwsgi vassals directory
  file: owner=matz group=http mode=750 state=directory path=/etc/uwsgi/vassals

- name: configure portfolio uwsgi
  template: src=uwsgi_config.ini.j2 dest=/etc/uwsgi/vassals/{{ app_name }}.ini owner=matz group=http mode=640

- name: nginx reload
  service: name=nginx state=reloaded
