---

- hosts: servers
  remote_user: matz
  vars:
    - app_name: fmexp-layout1
    - app_path: /srv/http/{{ app_name }}
    - instance_path: /var/{{ app_name }}
    - reset_db: false

  roles:
    - deploy
